### ISSUE TITLE
logging errors

### ISSUE THREAD

**Issue by sagol** [DwangoMediaVillage/pqkmeans#30]
`--- Logging error ---
Traceback (most recent call last):
  File "//.pyenv/versions/3.7.2/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "//.pyenv/versions/3.7.2/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "//.pyenv/versions/3.7.2/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "//.pyenv/versions/3.7.2/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting`

Lines like `logging.debug (" R: ", R.shape)` seem to be changed.

python 3.7.2

**Comment by matsui528** [comment]
Fixed in #31. Thanks!
