### ISSUE TITLE
Can not install through pip

### ISSUE THREAD

**Issue by Rhtyme** [DwangoMediaVillage/pqkmeans#45]
Thanks for this great library, but I could not really install it through pip. I have `cmake` installed in my ubuntu system, and when I try to install through `pip3.8 install pqkmeans` the error that I get :

```
(env_38) user@user-LPC:~/projects/tmp$ pip3.8 install pqkmeans
Collecting pqkmeans
  Using cached pqkmeans-1.0.5.tar.gz (161 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting scipy
  Using cached scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
Collecting numpy
  Using cached numpy-1.24.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Collecting texmex-python==1.0.0
  Using cached texmex_python-1.0.0.tar.gz (2.5 kB)
  Preparing metadata (setup.py) ... done
Collecting pipe
  Using cached pipe-2.0-py3-none-any.whl (8.8 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.2.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.8 MB)
Collecting lshash3
  Using cached lshash3-0.0.8.tar.gz (9.4 kB)
  Preparing metadata (setup.py) ... done
Collecting joblib>=1.1.1
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting bitarray
  Using cached bitarray-2.7.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (271 kB)
Building wheels for collected packages: pqkmeans
  Building wheel for pqkmeans (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pqkmeans (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [86 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/pqkmeans
      copying pqkmeans/evaluation.py -> build/lib.linux-x86_64-cpython-38/pqkmeans
      copying pqkmeans/__init__.py -> build/lib.linux-x86_64-cpython-38/pqkmeans
      creating build/lib.linux-x86_64-cpython-38/test
      copying test/__init__.py -> build/lib.linux-x86_64-cpython-38/test
      creating build/lib.linux-x86_64-cpython-38/pqkmeans/clustering
      copying pqkmeans/clustering/__init__.py -> build/lib.linux-x86_64-cpython-38/pqkmeans/clustering
      copying pqkmeans/clustering/cpp_implemented_clustering_sample.py -> build/lib.linux-x86_64-cpython-38/pqkmeans/clustering
      copying pqkmeans/clustering/pure_python_clustering_sample.py -> build/lib.linux-x86_64-cpython-38/pqkmeans/clustering
      copying pqkmeans/clustering/bkmeans.py -> build/lib.linux-x86_64-cpython-38/pqkmeans/clustering
      copying pqkmeans/clustering/pqkmeans.py -> build/lib.linux-x86_64-cpython-38/pqkmeans/clustering
      creating build/lib.linux-x86_64-cpython-38/pqkmeans/encoder
      copying pqkmeans/encoder/encoder_sample.py -> build/lib.linux-x86_64-cpython-38/pqkmeans/encoder
      copying pqkmeans/encoder/__init__.py -> build/lib.linux-x86_64-cpython-38/pqkmeans/encoder
      copying pqkmeans/encoder/itq_encoder.py -> build/lib.linux-x86_64-cpython-38/pqkmeans/encoder
      copying pqkmeans/encoder/encoder_base.py -> build/lib.linux-x86_64-cpython-38/pqkmeans/encoder
      copying pqkmeans/encoder/pq_encoder.py -> build/lib.linux-x86_64-cpython-38/pqkmeans/encoder
      creating build/lib.linux-x86_64-cpython-38/test/clustering
      copying test/clustering/test_pqkmeans.py -> build/lib.linux-x86_64-cpython-38/test/clustering
      copying test/clustering/__init__.py -> build/lib.linux-x86_64-cpython-38/test/clustering
      copying test/clustering/test_cpp_implemented_clustering_sample.py -> build/lib.linux-x86_64-cpython-38/test/clustering
      copying test/clustering/test_pure_python_clustering_sample.py -> build/lib.linux-x86_64-cpython-38/test/clustering
      copying test/clustering/test_bkmeans.py -> build/lib.linux-x86_64-cpython-38/test/clustering
      creating build/lib.linux-x86_64-cpython-38/test/encoder
      copying test/encoder/__init__.py -> build/lib.linux-x86_64-cpython-38/test/encoder
      copying test/encoder/test_pq_encoder.py -> build/lib.linux-x86_64-cpython-38/test/encoder
      copying test/encoder/test_encoder_sample.py -> build/lib.linux-x86_64-cpython-38/test/encoder
      copying test/encoder/test_itq_encoder.py -> build/lib.linux-x86_64-cpython-38/test/encoder
      running build_ext
      Traceback (most recent call last):
        File "/home/user/projects/tmp/env_38/bin/cmake", line 5, in <module>
          from cmake import cmake
      ModuleNotFoundError: No module named 'cmake'
      Traceback (most recent call last):
        File "/home/user/projects/tmp/env_38/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/user/projects/tmp/env_38/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/user/projects/tmp/env_38/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-5x4zvxen/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-5x4zvxen/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-5x4zvxen/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 76, in <module>
        File "/tmp/pip-build-env-5x4zvxen/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-5x4zvxen/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-5x4zvxen/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-5x4zvxen/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-5x4zvxen/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-5x4zvxen/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-5x4zvxen/normal/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/tmp/pip-build-env-5x4zvxen/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-5x4zvxen/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-5x4zvxen/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-5x4zvxen/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-5x4zvxen/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-5x4zvxen/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-5x4zvxen/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 37, in run
        File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pqkmeans
Failed to build pqkmeans
ERROR: Could not build wheels for pqkmeans, which is required to install pyproject.toml-based projects
```

How to fix it?

**Comment by Rhtyme** [comment]
thanks for your reply
